[package]
name = "twelve"
version = "0.1.0"
edition = "2021"

[dependencies]
async-signal = "0.2.5"
axum = "0.7.4"
envy = "0.4.2"
futures-lite = "2.2.0"
maud = "0.26.0"
serde = "1.0.196"
serde_json = "1.0.113"
thiserror = "1.0.56"
tokio = "1.36.0"
tower-service = "0.3.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
