[package]
name = "twelve"
version = "0.3.0"
description = "Twelve-factor app utilities for axum"
repository = "https://github.com/mbr/twelve-rs"
documentation = "https://docs.rs/twelve"
readme = "README.md"
keywords = ["axum", "twelve-factor", "web"]
categories = ["web-programming::http-server"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.80"
include = [
  "src/**/*",
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
]

[features]
postgres = ["dep:sec", "dep:sqlx"]

[dependencies]
axum = "0.8"
html-escape = "0.2"
sec = { version = "1", optional = true }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", default-features = false, features = ["postgres"], optional = true }
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "signal"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter"] }
